### PR TITLE
Update matching.py

### PR DESCRIPTION
**Pull request by Ankur-AVP-Patel**
Multimer generation optional
Amidase mass corrected
Multimer specific modifications now apply to all muropeptides.

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
I've not run the code but these look like sensible changes to correct hardcoded values and typos.

**Comment by bobturneruk** [comment]
@Ankur-AVP-Patel you'll probably want to `rebase` this branch, then force push, before merging. I can help.

**Comment by Ankur-AVP-Patel** [comment]
I believe the test file might need updating. This branch contained corrections to mass errors. If the test_output file was generated using older code then it will contain these errors in the output.

**Comment by Ankur-AVP-Patel** [comment]
I've included a new baseline_output file called baseline_output_v2. I haven't updated the regression test to check against this output just yet. Can you double check before making the change?

the test input will need to be changed to enable all search parameters are the new baseline file is generated using all of them enabled.  See below.

mod_test = ['Sodium','Potassium','Anhydro','DeAc','Deacetyl_Anhydro','Nude','Decay','Amidation','Amidase','Double_Anh']

**Comment by bobturneruk** [comment]
I think I've implemented your changes @Ankur-AVP-Patel - but the test still fails. I'll look into this - let me know if you have any ideas...

**Comment by bobturneruk** [comment]
P.S. it's fine to delete files that have previously been committed, we can always get them back. In fact, it's better to delete than rename or move.

**Comment by bobturneruk** [comment]
@Ankur-AVP-Patel - tests should now pass. Please ensure the output is scientifically correct before merging ('cos I have no idea!).

**Comment by bobturneruk** [comment]
What're these file for?

image

Do they duplicate the .ftrs file? Can we drop the ftrs?

**Pull request merged**
